world calculator {
    /// add two numbers
    export add: func(a: s32, b: s32) -> s32;

    /// subtract the second number from the first
    export subtract: func(a: s32, b: s32) -> s32;

    /// multiply two numbers
    export multiply: func(a: s32, b: s32) -> s32;

    /// divide the first number by the second
    export divide: func(a: s32, b: s32) -> s32;
}
