/// calculator operations
interface calculator {

    /// add two numbers
    add: func(a: s32, b: s32) -> s32;

    /// subtract the second number from the first
    subtract: func(a: s32, b: s32) -> s32;

    /// multiply two numbers
    multiply: func(a: s32, b: s32) -> s32;

    /// divide the first number by the second
    divide: func(a: s32, b: s32) -> s32;
}

/// the calculator world
world calculator-world {
    export calculator;
}
