interface publisher {
    publish: func(message: string) -> result<s64, string>;
}

world valkey-publisher-world {
    import wasi:config/store@0.2.0-rc.1;
    import componentized:valkey/store;
    export publisher;
}
